name: Tokens
version: ${project.version}
main: net.thirdshift.tokens.Tokens
softdepend: [Factions, mcMMO, Vault, CombatLogX, PlaceholderAPI]
api-version: 1.14
authors: [TheCoolestPaul]
description: Adding another currency into Minecraft
commands:
  tokens:
    permission: tokens.use
    description: Main command for Tokens
    usage: /tokens help
  redeem:
    permission: tokens.redeem
    description: Command for redeeming Tokens
    usage: /redeem
permissions:
  tokens.use:
    default: true
    description: Required to use /tokens
  tokens.redeem:
    default: true
    description: Required to use /redeem
  tokens.give:
    default: true
    description: Required to use /tokens give (target player) (token amount)
  tokens.others:
    default: false
    description: Required to use /tokens (player name)
  tokens.reload:
    default: false
    description: Required to use /tokens reload
  tokens.set:
    default: false
    description: Required to use /tokens set
  tokens.add:
    default: false
    description: Required to use /tokens add
  tokens.remove:
    default: false
    description: Required to use /tokens remove